import Header from './Header';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <title>Wassem Todos</title>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
